name: Publish Website
on:
  push:
    branches: [master]

jobs:
  publish-website:
    runs-on: ubuntu-latest
    name: Publish Website
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache build
        uses: actions/cache@v4
        with:
          path: .cache/webpack
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Build Website
        run: |
          npm run build
          sed -i "s/#DEVELOPMENT_BUILD#/$(git rev-parse --short ${{ github.sha }})/g" ./_site/script.js
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: _site
          single-commit: true
          git-config-name: 'github-actions[bot]'
          git-config-email: 'github-actions[bot]@users.noreply.github.com'
